workflows:
  multi-platform-build:
    name: PCB AOI Multi-Platform
    instance_type: mac_mini_m2 # M2 is needed for macOS/iOS builds
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - common_env
    scripts:
      - name: Fetch Dependencies
        script: |
          flutter pub get
      - name: Hard Reset Android
        script: |
          # This forces Flutter to recreate the hidden v2 embedding files
          flutter clean
          rm -rf android/.gradle
          rm -rf android/app/build
      - name: Build Android APK
        script: |
          flutter build apk --release 
      - name: Build macOS App
        script: |
          flutter build macos --release --no-codesign
      - name: Build iOS App
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/**/outputs/**/*.apk
      - build/macos/Build/Products/Release/*.app
      - build/ios/iphoneos/*.ipa
