workflows:
  multi-platform-build:
    name: PCB AOI Multi-Platform
    instance_type: mac_mini_m2 # M2 is needed for macOS/iOS builds
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - common_env
    scripts:
      - name: Fetch Dependencies
        script: |
          flutter pub get
      - name: Force Clean Build
        script: |
         # This wipes out any hidden 'v1' leftovers
          flutter clean
      - name: Build Android APK
        script: |
          flutter build apk --release 
      - name: Build macOS App
        script: |
          flutter build macos --release --no-codesign
      - name: Build iOS App
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/**/outputs/**/*.apk
      - build/macos/Build/Products/Release/*.app
      - build/ios/iphoneos/*.ipa
